services:
  backend:
    image: kunalwankhade/onebox-backend:latest
    container_name: onebox-backend
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: onebox-qdrant
    ports:
      - "6333:6333"
    restart: always

